export const contactsList = [
  {
    id: '1',
    name: 'John Smith',
    title: 'Graphics designer',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/john-smith.jpg',
  },
  {
    id: '2',
    name: 'Alex Johnatan',
    title: 'CEO',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/alex-johnatan.jpg',
  },
  {
    id: '3',
    name: 'Monica Smith',
    title: 'Marketing Manager',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/monica-smith.jpg',
  },
  {
    id: '4',
    name: 'Michael Zimber',
    title: 'Sales manager',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/michael-zimber.jpg',
  },
  {
    id: '5',
    name: 'Sandra Smith',
    title: 'Graphics Designer',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/sandra-smith.jpg',
  },
  {
    id: '6',
    name: 'Janet Carton',
    title: 'Graphics Designer',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/janeth-carton.jpg',
  },
  {
    id: '7',
    name: 'Alex Johnatan',
    title: 'CEO',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/alex-johnatan.jpg',
  },
  {
    id: '8',
    name: 'Alex Johnatan',
    title: 'CEO',
    phoneNumber: `(123) 456-7890`,
    jobAddress: 'Riviera State 32/106',
    dummyBoldTitle: 'Twitter, Inc.',
    homeAddress: '795 Folsom Ave, Suite 600 San Francisco CA 94107',
    img: '/assets/alex-johnatan.jpg',
  },
];
